### ISSUE TITLE
Persist cache in the file system

### ISSUE THREAD

**Issue by jviotti** [jviotti/ghrequest#1]
Currently, the cache is saved in memory, therefore if the application exists and starts again, it will forget all saved responses.

It might be nice to persist this in the file system in order to account for the above case, although not sure how useful this would be, or if is even desirable by users.

I'm also wondering about what would be the best method to do this (maybe something like https://www.npmjs.com/package/node-storage?).

**Comment by kounelios13** [comment]
So when should the cache be saved on the disk?Should we detect `process.on('exit')`?

**Comment by jviotti** [comment]
The module should mirror its internal cache to the disk as soon as any operation is complete.

**Comment by kounelios13** [comment]
Doesn't sound that hard I will have a look at it in the morning but I can't make any 
tests

**Comment by kounelios13** [comment]
@jviotti Can you help me with the tests?

**Comment by jviotti** [comment]
Closing stale issues
